//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenNBas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int usuarioId { get; set; }
        public string nombre { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> tokenExpira { get; set; }
        public Nullable<bool> estatus { get; set; }
        public string email { get; set; }
        public string psw { get; set; }
    }
}
